

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        MONGODB_URL: ${MONGODB_URL}
        JWT_SECRET: ${JWT_SECRET}
        GOOGLE_MAPS_API: ${GOOGLE_MAPS_API}
        
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_MAPS_API=${GOOGLE_MAPS_API}
    ports:
      - "3000:3000"  